export const GET_LEADERBOARD_SUCCESS = 'GET_LEADERBOARD_SUCCESS';
export const GET_GRID_SUCCESS = 'GET_GRID_SUCCESS';
export const GET_OPPONENT_EMPTY_GRID_SUCCESS = 'GET_OPPONENT_EMPTY_GRID_SUCCESS';
export const GET_ONLINE_USERS_SUCCESS = 'GET_ONLINE_USERS_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_OPPONENT_SUCCESS = 'GET_OPPONENT_SUCCESS';